"0,0,0":
  id: 1
  premium: false
  name: Black
"60,60,60":
  id: 2
  premium: false
  name: Dark Gray
"120,120,120":
  id: 3
  premium: false
  name: Gray
"210,210,210":
  id: 4
  premium: false
  name: Light Gray
"255,255,255":
  id: 5
  premium: false
  name: White
"96,0,24":
  id: 6
  premium: false
  name: Deep Red
"237,28,36":
  id: 7
  premium: false
  name: Red
"255,127,39":
  id: 8
  premium: false
  name: Orange
"246,170,9":
  id: 9
  premium: false
  name: Gold
"249,221,59":
  id: 10
  premium: false
  name: Yellow
"255,250,188":
  id: 11
  premium: false
  name: Light Yellow
"14,185,104":
  id: 12
  premium: false
  name: Dark Green
"19,230,123":
  id: 13
  premium: false
  name: Green
"135,255,94":
  id: 14
  premium: false
  name: Light Green
"12,129,110":
  id: 15
  premium: false
  name: Dark Teal
"16,174,166":
  id: 16
  premium: false
  name: Teal
"19,225,190":
  id: 17
  premium: false
  name: Light Teal
"40,80,158":
  id: 18
  premium: false
  name: Dark Blue
"64,147,228":
  id: 19
  premium: false
  name: Blue
"96,247,242":
  id: 20
  premium: false
  name: Cyan
"107,80,246":
  id: 21
  premium: false
  name: Indigo
"153,177,251":
  id: 22
  premium: false
  name: Light Indigo
"120,12,153":
  id: 23
  premium: false
  name: Dark Purple
"170,56,185":
  id: 24
  premium: false
  name: Purple
"224,159,249":
  id: 25
  premium: false
  name: Light Purple
"203,0,122":
  id: 26
  premium: false
  name: Dark Pink
"236,31,128":
  id: 27
  premium: false
  name: Pink
"243,141,169":
  id: 28
  premium: false
  name: Light Pink
"104,70,52":
  id: 29
  premium: false
  name: Dark Brown
"149,104,42":
  id: 30
  premium: false
  name: Brown
"248,178,119":
  id: 31
  premium: false
  name: Beige
"170,170,170":
  id: 32
  premium: true
  name: Medium Gray
"165,14,30":
  id: 33
  premium: true
  name: Dark Red
"250,128,114":
  id: 34
  premium: true
  name: Light Red
"228,92,26":
  id: 35
  premium: true
  name: Dark Orange
"214,181,148":
  id: 36
  premium: true
  name: Light Tan
"156,132,49":
  id: 37
  premium: true
  name: Dark Goldenrod
"197,173,49":
  id: 38
  premium: true
  name: Goldenrod
"232,212,95":
  id: 39
  premium: true
  name: Light Goldenrod
"74,107,58":
  id: 40
  premium: true
  name: Dark Olive
"90,148,74":
  id: 41
  premium: true
  name: Olive
"132,197,115":
  id: 42
  premium: true
  name: Light Olive
"15,121,159":
  id: 43
  premium: true
  name: Dark Cyan
"187,250,242":
  id: 44
  premium: true
  name: Light Cyan
"125,199,255":
  id: 45
  premium: true
  name: Light Blue
"77,49,184":
  id: 46
  premium: true
  name: Dark Indigo
"74,66,132":
  id: 47
  premium: true
  name: Dark Slate Blue
"122,113,196":
  id: 48
  premium: true
  name: Slate Blue
"181,174,241":
  id: 49
  premium: true
  name: Light Slate Blue
"219,164,99":
  id: 50
  premium: true
  name: Light Brown
"209,128,81":
  id: 51
  premium: true
  name: Dark Beige
"255,197,165":
  id: 52
  premium: true
  name: Light Beige
"155,82,73":
  id: 53
  premium: true
  name: Dark Peach
"209,128,120":
  id: 54
  premium: true
  name: Peach
"250,182,164":
  id: 55
  premium: true
  name: Light Peach
"123,99,82":
  id: 56
  premium: true
  name: Dark Tan
"156,132,107":
  id: 57
  premium: true
  name: Tan
"51,57,65":
  id: 58
  premium: true
  name: Dark Slate
"109,117,141":
  id: 59
  premium: true
  name: Slate
"179,185,209":
  id: 60
  premium: true
  name: Light Slate
"109,100,63":
  id: 61
  premium: true
  name: Dark Stone
"148,140,107":
  id: 62
  premium: true
  name: Stone
"205,197,158":
  id: 63
  premium: true
  name: Light Stone